### ISSUE TITLE
Exclude folders with wildcards

### ISSUE THREAD

**Issue by oeb25** [yosssi/goat#17]
Being able to exclude entire folders seems very beneficial! This comes in handy when working with package managers like `npm` or go's `vendor` directory among others.

Proposed syntax:
```
watchers:
 - extension: js
   tasks:
    - command: npm build
   directory: js
   excludes:
    - node_modules/*
```

Or maybe have a new field be a regex, to be used in place of both `extension` and `excludes`
```
watchers:
 - match: /(?!(\/?node_modules).)\/.+\.js$/
   tasks:
    - command: npm build
```

or alternatively with globs and `not_matches`
```
watchers:
 - matches: /**/*.js
   not_matches: */node_modules/*
   tasks:
    - command: npm build
```

Thoughts on this? I'd gladly create a pull request if desired.
